#!/bin/bash
if [[ "${GITHUB_ACTIONS:-false}" != "true" ]]; then
  set -x
fi
RELEASE_TAG="6.1.1.7"
export RELEASE_TAG
if [[ "${GITHUB_ACTIONS:-false}" == "true" && -n "${GHA_DATE_TAG:-}" ]]; then
  [[ "${GHA_DATE_TAG}" =~ ^[0-9]{6}$ ]] || {
    echo "GHA_DATE_TAG must use MMDDYY format" >&2
    exit 1
  }
  DATE_TAG=${GHA_DATE_TAG}
else
  DATE_TAG=$(date +"%m%d%y")
fi
TRAVIS_TAG_WITH_UPSTREAM_ID=${TRAVIS_TAG}.${UPSTREAM_ID}
TRAVIS_TAG_WITH_UPSTREAM_ID_DATE_TRAVIS_BUILD_NUMBER=${TRAVIS_TAG_WITH_UPSTREAM_ID}.${DATE_TAG}.${TRAVIS_BUILD_NUMBER}
GHA_DATED_IMAGE_TAG=${TRAVIS_TAG_WITH_UPSTREAM_ID_DATE_TRAVIS_BUILD_NUMBER}
IMAGE_TAG=${TRAVIS_TAG_WITH_UPSTREAM_ID}
UPSTREAM_IMAGE_TAG=${RELEASE_TAG}.${UPSTREAM_ID}
UPSTREAM_IMAGE_Z_TAG=${RELEASE_TAG}.${UPSTREAM_ID}.z
export GHA_DATED_IMAGE_TAG UPSTREAM_IMAGE_Z_TAG
IMAGE_Z_TAG=${TRAVIS_TAG_WITH_UPSTREAM_ID}.z
RELEASE_Z_TAG=${RELEASE_TAG}.z
RC_PREFIX=${RELEASE_TAG}rc
RC_REGEX=${RC_PREFIX}[0-9]+
QUAY_REGISTRY=quay.io/noirolabs
QUAY_NOIRO_REGISTRY=quay.io/noiro
DOCKER_REGISTRY=docker.io/noiro
CICD_STATUS_REPO="https://github.com/noironetworks/cicd-status.git"
CICD_STATUS_REPO_DIR="cicd-status"
export CICD_STATUS_REPO_DIR
