#!/bin/bash
set -x
RELEASE_TAG="6.1.1.3"
export RELEASE_TAG
DATE_TAG=$(date +"%m%d%y")
TRAVIS_TAG_WITH_UPSTREAM_ID=${TRAVIS_TAG}.${UPSTREAM_ID}
TRAVIS_TAG_WITH_UPSTREAM_ID_DATE_TRAVIS_BUILD_NUMBER=${TRAVIS_TAG_WITH_UPSTREAM_ID}.${DATE_TAG}.${TRAVIS_BUILD_NUMBER}
IMAGE_TAG=${TRAVIS_TAG_WITH_UPSTREAM_ID}
UPSTREAM_IMAGE_TAG=${RELEASE_TAG}.${UPSTREAM_ID}
UPSTREAM_IMAGE_Z_TAG=${RELEASE_TAG}.${UPSTREAM_ID}.z
IMAGE_Z_TAG=${TRAVIS_TAG_WITH_UPSTREAM_ID}.z
RELEASE_Z_TAG=${RELEASE_TAG}.z
RC_PREFIX=${RELEASE_TAG}rc
RC_REGEX=${RC_PREFIX}[0-9]+
QUAY_REGISTRY=quay.io/noirolabs
QUAY_NOIRO_REGISTRY=quay.io/noiro
DOCKER_REGISTRY=docker.io/noiro
CICD_STATUS_REPO="https://github.com/noironetworks/cicd-status.git"
