#!/bin/bash
set -x

DATE_TAG=$(date +"%m%d%y")
TRAVIS_TAG_WITH_UPSTREAM_ID=${TRAVIS_TAG}.${UPSTREAM_ID}
TRAVIS_TAG_WITH_UPSTREAM_ID_DATE_TRAVIS_BUILD_NUMBER=${TRAVIS_TAG_WITH_UPSTREAM_ID}.${DATE_TAG}.${TRAVIS_BUILD_NUMBER}
IMAGE_TAG=${TRAVIS_TAG_WITH_UPSTREAM_ID}
QUAY_REGISTRY=quay.io/noirolabs
DOCKER_REGISTRY=docker.io/noiro
